# -*- coding: utf-8 -*-
"""13Jan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_-Aw2jUdiqxpaxgIlTiwQHJpqNnScTo

# Ques : Count Number of lines , Seperate all lines fron (.) , Count number of lines starting with letter A and Y

Reading a file
"""

f = open("NewFile.txt", "r")
f.read()

"""No. of sentences"""

f = open("NewFile.txt", "r")
c=f.read()
sentences = c.split(".")
setences = [sentence.strip() for sentence in sentences if sentence.strip()]
print(setences)

total_sentences = len(setences)
print(total_sentences)

"""Count no of sentence starting with A


"""

f = open("NewFile.txt", "r")
c=f.read()
sentences = c.split(".")
setences = [sentence.strip() for sentence in sentences if sentence.strip()]

sentence_ALetter = []
for sentence in setences:
    if sentence.lower().startswith('a'):
        sentence_ALetter.append(sentence)
print(sentence_ALetter)
count_ALetter = len(sentence_ALetter)
print(count_ALetter)

"""Count no of setence using y"""

f = open("NewFile.txt", "r")
c=f.read()
sentences = c.split(".")
setences = [sentence.strip() for sentence in sentences if sentence.strip()]

sentence_ALetter = []
for sentence in setences:
    if sentence.lower().startswith('y'):
        sentence_ALetter.append(sentence)
print(sentence_ALetter)
count_ALetter = len(sentence_ALetter)
print(count_ALetter)

"""#Advanced file system using all modes

"""

f = "Newfile1.txt"
def writefile():
  f=open("Newfile1.txt","w")
  f.write("New Line using W .")
  print("Write Operation done.")
  f.close()
def readfile():
  f=open("Newfile1.txt","r")
  print(f.read())
  print("Read Operation done.")
  f.close()
def appendfile():
  f=open("Newfile1.txt","a")
  f.write("New Line using A .")
  print("Append Operation done.")
  f.close()
def read_writefile():
  f=open("Newfile1.txt","r+")
  print(f.read())
  f.write("New Line using R+ .")
  print("Read and Write Operation done.")
  f.close()
def writeplusfile():
  f=open("Newfile1.txt","w+")
  f.write("New Line using W+ .")
  print(f.read())
  print("Write and Read Operation done.")
  f.close()
def readappendfile():
  f=open("Newfile1.txt","a+")
  f.write("New Line using A+ .")
  print(f.read())
  print("Read and Append Operation done.")
  f.close()

print("\n1.Write Operation")
print("\n2.Read Operation")
print("\n3.Append Operation")
print("\n4.Read and Write Operation")
print("\n5.Write and Read Operation")
print("\n6.Read and Append Operation")

choice= int(input("Enter your choice: (1-6)"))

if choice==1:
  writefile()
elif choice ==2:
  readfile()
elif choice ==3:
  appendfile()
elif choice ==4:
  read_writefile()
elif choice ==5:
  writeplusfile()
elif choice ==6:
  readappendfile()
else:
  print("\n\nInvalid choice....")