# -*- coding: utf-8 -*-
"""1Jan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1577IzJXAlm2nOHgYWCkQ9CCX0WiGpOC0

#Calculator Using Functions
"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Error: Division by zero"

def calculator():
    print("Select operation:")
    print("1. Add\n2. Subtract\n3. Multiply\n4. Divide")
    choice = input("Enter choice (1/2/3/4): ")

    if choice in ['1', '2', '3', '4']:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print("Result:" ,add(num1, num2))
        elif choice == '2':
            print("Result:",subtract(num1, num2))
        elif choice == '3':
            print("Result:",multiply(num1, num2))
        elif choice == '4':
            print("Result:",divide(num1, num2))
    else:
        print("Invalid input")

calculator()

"""#Quiz Using Function"""

def ask(question, answer):
    return input(question).lower() == answer.lower()

def quiz():
    score = 0
    score += ask("What is the capital of France? ", "Paris")
    score += ask("Which planet is known as the Red Planet? ", "Mars")
    score += ask("What is 5 + 3? ", "8")
    print(f"Your score is {score}/3")

quiz()