# -*- coding: utf-8 -*-
"""23DLectureork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11k-ziF8DjD-fScYHHeWCM2yBq7xU1eTC
"""

row=int(input("Enter the number of rows:"))
col=int(input("Enter the number of columns:"))
total_desk=row*col
print("Total number of desks:",total_desk)

number_of_guest = 0
while True :
  code=int(input("Enter the autheciation code: "))
  if code == -1:
    print("\nTotal number of guests: ",number_of_guest)
    break
  elif code == 0:
    print("Authenciation granted \n Door opened.")
  elif code == 1:
    number_of_guest = number_of_guest + 1
    print("Door opened \n Welcome to the Party, We hope you have fun.")
  else :
    print("You have entered the invalid code.")

Start = int(input("Enter the start of range: "))
End = int(input("Enter the end of range: "))
print("Even numbers are:")
for num in range(Start, End + 1):
    if num % 2 == 0:
        print(num, end=" ")
print("\nOdd numbers are:")
for num in range(Start, End + 1):
    if num % 2 != 0:
        print(num, end=" ")

essay=input("Enter the essay: ")
Word_count = 0
for char in essay:
    if char == ' ':
        Word_count += 1
if Word_count > 250:
  print("The essay meets the minimum number of count.")
  print("The number of words in essay :", Word_count)
else :
  print("The number of words in essay :", Word_count)
  print("The essay does not meet the minimum number of count.")

num = int(input("Enter the number: "))
if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")

student_data = {}
student_data.update({10: "Arjun", 11: "Rajesh", 12: "Rajesh", 13: "Sathish"})
while True:
      print("\n1. Add Student\n2. Send Message\n3. Display Students\n4. Exit")
      choice = int(input("Choose an option: "))

      if choice == 1:
            student_id = int(input("Enter Student ID: "))
            name = input("Enter Student Name: ")
            student_data[student_id] = name
            print("Student",name," added with ID ",student_id )
      elif choice == 2:
            for student_id in student_data:
                print("Message sent to: ",student_id)
      elif choice == 3:
            print("\nStudent Details:")
            for student_id, name in student_data.items():
                print("ID: ", student_id,", Name: ",name)
      elif choice == 4:
            break
      else:
            print("Invalid option!")