# -*- coding: utf-8 -*-
"""2Jan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zpvn0D9IYADHzIwM8wtz850DcjydgrON

Question 1 : Pastel Text Box
Chirag was given a list containing n numbers. His teacher asked him to find the product of all the elements present in the list. He did it perfectly when the list was small. As the size of the next lists were becoming larger,he found it difficult to calculate the product. He thought of creating a python program that gets a list as argument and calculates the product and displays the result.But he is not good at function concepts. Help him to create a function to do the above.
"""

def calculate_product(n):
  product = 1
  for i in n:
    product *= i
  return product
list1= [1,2,3,4,5]
result = calculate_product(list1)
print("The product of List :" ,result)

"""Question 2 :  Sahil came to know about Pascal’s triangle. He tries the small patterns of pascal’s triangle. But he was not sure how the triangle looks when the number of rows were increased. Help him to create a function which gets the number of rows as input from the user and prints the pascal’s triangle upto that row.


"""

n = int(input("Enter the number of rows :"))
for i in range(1, n+1):
    for j in range(0, n-i+1):
        print(' ', end='')
    C = 1
    for j in range(1, i+1):
        print(" ", C,  end='')
        C = C * (i - j) // j
    print()

"""Question 3 :  Retro Frame Text Box
Nidhi is writing a program to count the number of digits in a number given by user. But she got stuck in the middle. Help her to create a function that counts the number of digits in a given number.
"""

def count_digits(number):
    return len(str(number))

num = int(input("Enter a number: "))
print("The number of digits is:", count_digits(num))

"""Question 4 :
Mahesh learnt about LCM of numbers and is eager to find LCM for more numbers. But he finds it tough to calculate the LCM for larger numbers. Help him to create a function that gets two numbers as input, finds the LCM of those two numbers and displays the result as output.
"""

def find_lcm(a, b):
    lcm = a * b
    for i in range(1, lcm + 1):
        if i % a == 0 and i % b == 0:
            return i

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
print("The LCM of", num1, "and", num2, "is:", find_lcm(num1, num2))