# -*- coding: utf-8 -*-
"""31dEC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jObuS_XEOICtFUk8WMMYKXPjY25v7WD

# Questions

Create a sum of 100 numbers program using for loop and the while loop separately

Create a quiz program using while loop

Create a chatbot program using while loop

Create atm program

Sum using For Loop
"""

sum=0
for i in range(1,101):
  sum = sum + i
print("Total Sum of 100 number :", sum)

"""Sum using while loop"""

i=1
sum=0
while i<=100:
  sum = sum + i
  i = i + 1
print("Total Sum of 100 number :", sum)

"""# Quiz"""

questions = [
    {"question": "What is the capital of France?", "answer": "Paris"},
    {"question": "What is 5 + 7?", "answer": "12"},
]

score = 0
index = 0

print("Welcome to the Quiz! Let's begin.\n")

while index < len(questions):
    print("Q", index + 1, ":", questions[index]['question'])
    user_answer = input("Your answer: ").strip()

    if user_answer.lower() == questions[index]['answer'].lower():
        print("Correct!\n")
        score += 1
    else:
        print("Wrong! The correct answer was:", questions[index]['answer'], "\n")

    index += 1

print("Quiz Over! Your final score is", score, "/", len(questions))

"""# Chatbot"""

print("Hello! I am your friendly chatbot. Let's get to know each other!")
print("Type 'exit' anytime to end the chat.\n")

while True:

    user_name = input("Chatbot: What is your name? ")
    if user_name.lower() == "exit":
        print("Chatbot: Goodbye! Have a great day!")
        break
    print("Chatbot: Nice to meet you,", user_name, "!")

    user_age = input(f"Chatbot: How old are you, {user_name}? ")
    if user_age.lower() == "exit":
        print("Chatbot: Goodbye! Have a great day!")
        break
    print("Chatbot: So you're", user_age, "years old!")

    user_study = input(f"Chatbot: What are you currently studying, {user_name}? ")
    if user_study.lower() == "exit":
        print("Chatbot: Goodbye! Have a great day!")
        break
    print("Chatbot: Studying", user_study, "sounds exciting!")

    user_hobbies = input(f"Chatbot: What are your hobbies, {user_name}? ")
    if user_hobbies.lower() == "exit":
        print("Chatbot: Goodbye! Have a great day!")
        break
    print("Chatbot: Wow! I also like", user_hobbies, ".")

    print("\nChatbot: Here's what I learned about you:")
    print("Name:", user_name)
    print("Age:", user_age)
    print("Studying:", user_study)
    print("Hobbies:", user_hobbies)
    print("\nChatbot: Thanks for sharing! Have a wonderful day!\n")
    break

"""# ATM"""

balance = 1000

while True:
    print("\nATM Menu:")
    print("1. Check Balance \n2. Deposit \n3. Withdraw \n4. Exit")
    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        print("Your current balance is:", balance)

    elif choice == '2':
        deposit = int(input("Enter the amount to deposit: "))
        balance += deposit
        print(f"Deposited {deposit}. Your new balance is: {balance}")

    elif choice == '3':
        withdraw = int(input("Enter the amount to withdraw: "))
        if withdraw > balance:
            print("Insufficient balance!")
        else:
            balance -= withdraw
            print(f"Withdrew {withdraw}. Your new balance is: {balance}")

    elif choice == '4':
        print("Exiting ATM. Have a great day!")
        break

    else:
        print("Invalid choice. Please try again.")