# -*- coding: utf-8 -*-
"""31Jan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-k1Yqk1ZvcruKSjck-IgsTbAWhO5mJK1
"""

import json
import requests

url = "https://jsonplaceholder.typicode.com/comments"

def get_data(comment_id=None):
    URL = f"{url}/{comment_id}" if comment_id else url
    response = requests.get(URL)
    print("\nGET Response:")
    print(json.dumps(response.json(), indent=4))

def post_data():
    new_comment = {
        "postId": 1,
        "name": "id labore ex et quam laborum",
        "email": "Eliseo@gardner.biz",
        "body": "This is a new comment."
    }
    response = requests.post(url, json=new_comment)
    response_data = response.json()
    response_data["id"] = 10
    print("\nPOST Response (Modified):")
    print(json.dumps(response_data, indent=4))

def put_data(comment_id):
    updated_comment = {
        "postId": 1,
        "name": "Abhinav",
        "email": "Abhinavrorms7@gmail.com",
        "body": "This is a fully updated comment."
    }
    URL = f"{url}/{comment_id}"
    response = requests.put(URL, json=updated_comment)
    print("\nPUT Response:")
    print(json.dumps(response.json(), indent=4))

def patch_data(comment_id):
    partial_update = {
        "body": "This comment has been partially updated."
    }
    URL = f"{url}/{comment_id}"
    response = requests.patch(URL, json=partial_update)
    print("\nPATCH Response:")
    print(json.dumps(response.json(), indent=4))

def delete_data(comment_id):
    URL = f"{url}/{comment_id}"
    response = requests.delete(URL)
    print("\nDELETE Response:")
    print("Status Code:", response.status_code)

get_data(1)
post_data()
put_data(1)
patch_data(1)
delete_data(1)