# -*- coding: utf-8 -*-
"""9Jan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jUBVuP20eHe5cW4HRwITgX8uQc12wKA

Read file
"""

f = open("new.txt","r")
print(f.read())

"""Read first line"""

f = open("new.txt","r")
print(f.readline())

"""Read line by line"""

f = open("new.txt","r")
print(f.readlines())

"""Writing in file"""

f = open("new.txt","w")
f.write("Hello World")
f.close()
f = open("new.txt","r")
print(f.read())

"""Apppend new data in file"""

f = open("new.txt","a")
f.write(" New data")
f.close()
f = open("new.txt","r")
print(f.read())

"""Read and write using W+"""

f = open("new.txt","w+")
f.write(" add using w+ mode. ")
f.close()
f = open("new.txt","r")
print(f.read())

"""Read and write using R+"""

f = open("new.txt","r+")
f.write(" add using r+ mode. ")
f.close()
f = open("new.txt","r")
print(f.read())

"""Append and read data in file using A+ mode


"""

f = open("new.txt","a+")
f.write("\n add new data using a+ mode. ")
f.close()
f = open("new.txt","r")
print(f.read())

try:
  f = open("new.txt","r")
  print(f.read())
except:
  print("No file exists.")
finally:
  f.close()

try:
  f = open("new1.txt","r")
  print(f.read())
except:
  print("No file exists.")
finally:
  f.close()

f= open("new.txt","w")
f.write("New!things goona happen IN 2025 $@.")
f.close()
f = open("new.txt","r")
uppercase_count = 0
lowercase_count = 0
number_count = 0
special_char_count = 0
for char in f.read():
  if char.isupper():
    uppercase_count += 1
  elif char.islower():
    lowercase_count += 1
  elif char.isdigit():
    number_count += 1
  else:
    special_char_count += 1
print("     File Complete Info :    \n ")
print("Uppercase Count : ",uppercase_count)
print("Lowercase Count : ",lowercase_count)
print("Number Count : ",number_count)
print("Special Character Count : ",special_char_count)
print(f.read())