# -*- coding: utf-8 -*-
"""LectureQues19D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQ-3FiQSe6_zAvXs_v8u8EmiO53FIvMN

# List
"""

list1=["Abhinav","Abhishek","Asmit"]
print(list1)
print(len(list1))
print(type(list1))

list1.append("Vishal")
print(list1)

list1.insert(0,"Pranav")
print(list1)

"""# Remove operations"""

list1.remove("Asmit")
print(list1)

list1.pop()
print(list1)

list1.pop(0)
print(list1)

del list1[0]
print(list1)

"""# Loops in Lists"""

list1=["Abhinav","Abhishek","Asmit"]
for x in list1:
  print(x)

i=0
while i < len(list1):
  print(list1[i])
  i=i+1

"""# Sorting list"""

list1.sort() #Ascending order
print(list1)
list2=[100,50,65,82,23]
list2.sort()
print(list2)

list1.sort(reverse=True)  #Descending order
print(list1)
list2.sort(reverse=True)
print(list2)

list1.reverse()
list2.reverse()
print(list1)
print(list2)

"""#Copy List"""

list1 = ["Abhinav","Asmit","Pranav"]
list2= list1.copy()
print(list2)

list1 = ["Abhinav","Asmit","Pranav"]
list2= list(list1)
print(list2)

"""#Join Lists"""

list1=['a','b','c']
list2=[1,2,3]
list3=list1+list2
print(list3)

list1=['a','b','c']
list2=[1,2,3]
for i in list2:
  list1.append(i)
print(list1)

list1=['a','b','c']
list2=[1,2,3]
list1.extend(list2)
print(list1)

"""# Sets"""

s ={"a","b","c",1,2,3}
print(s)

for i in s:
  print(i)

s.add("d")
print(s)

"""# join set"""

s={"a","b","c",1,2,3}
s1={4,5,6}
s.update(s1)
print(s)

s={"a","b"} #union
s1={1,2,3}
s2= s | s1
print(s2)

s={"a","b"} #union
s1={1,2,3}
s2=s.union(s1)
print(s2)

s={"a","b",1} #intersection
s1={1,2,3}
s2= s.intersection(s1)
print(s2)

s={"a","b",2} #intersection
s1={1,2,3}
s2= s & s1
print(s2)

s={"a","b",1} #difference
s1={1,2,3,"b"}
s2= s.difference(s1)
print(s2)

s={"a","b",2} #difference
s1={1,2,3 ,"b"}
s2= s - s1
print(s2)

"""## Delete in sets"""

s.remove(1)
print(s)

s.discard(2)
print(s)

s.pop()
print(s)

"""# Tuple"""

t=('a','b','c','d')
print(t)
print(len(t))
print(type(t))

print(t[0])
print(t[1])
print(t[2])
print(t[3])
print(t[-1])

"""# Updating tuple using lists"""

t1=("Abhinav","Abhisek","Manik")
t2=list(t1)
t2[0]="Avni"
t1=tuple(t2)
print(t1)

"""# Adding more items in tuple"""

print(t1)
print(type(t1))
t3=list(t1)
t3.append("Pranav")
t1=tuple(t3)
print(t1)
print(type(t1))

"""# Loop in tuple"""

for i in t1:
  print(i)

i=0
while i < len(t1):
  print(t1[i])
  i=i+1

"""# Dictonary"""

Dict1={1:"Abhinav",2:"Asmit",3:"Pranav"}
print(Dict1)
print(type(Dict1))

Dict1.update({4:"Vishal"})
print(Dict1)

Dict1.values()

Dict1.popitem()
print(Dict1)

Dict1.pop(3)
print(Dict1)

Dict1.update({1:"Avni"})
print(Dict1)

for i in Dict1:
  print(Dict1[i])

